// 基于 mobileApi.json 生成的教练端 Mock 数据

// ============ 教练信息 CoachVO ============
export const mockCoachProfile = {
  id: 101,
  userId: 1001,
  coachNo: "COACH-2024-001",
  realName: "王建国",
  phone: "138****8888",
  coachType: 1,
  coachTypeText: "全职",
  coachStatus: 1,
  coachStatusText: "可排课",
  specialty: "篮球 · 体能训练 · 游泳",
  experience: 8,
  education: "体育学院本科",
  introduction:
    "国家级篮球教练员资质，从事青少年篮球训练8年，曾带队参加全市青少年篮球联赛并获得冠军。擅长因材施教，注重基础技术和团队协作精神培养。",
  certificate: "国家职业体育教练员证,游泳救生员证,体能训练师证",
  completedSessions: 1248,
  rating: 4.9,
  coachRole: 1,
  status: 1,
}

// ============ 课程数据 CourseVO ============
export const mockCourses = [
  {
    id: 1,
    courseName: "青少年篮球训练营",
    courseType: 3,
    courseTypeText: "训练营",
    courseCategory: "篮球",
    courseLevel: 1,
    courseLevelText: "初级",
    durationMinutes: 90,
    capacity: 20,
    enrollCount: 15,
    enrollmentRequirements: "8-14岁青少年，有基础运动能力",
    price: 2800,
    coachId: 101,
    coachName: "王建国",
    location: "A馆篮球场",
    startTime: "2024-09-01T09:00:00",
    endTime: "2025-06-30T10:30:00",
    status: 1,
    statusText: "进行中",
    courseDesc:
      "本课程旨在培养青少年篮球基本技能和团队协作精神，通过系统训练提升运动能力。内容涵盖运球、传球、投篮、防守及实战对抗。",
    courseDetail:
      "训练内容分为三个阶段：\n第一阶段（1-16课时）：基础技术——运球、传球、步法；\n第二阶段（17-32课时）：进阶技术——投篮、防守、配合跑位；\n第三阶段（33-48课时）：实战对抗——3对3、5对5比赛及战术演练。",
    totalSessions: 48,
    completedSessions: 32,
    schedule: "周二、周四、周六",
    scheduleTime: "09:00 - 10:30",
    studentIds: [1, 5, 6, 8, 9, 10, 11, 12],
  },
  {
    id: 2,
    courseName: "私教体能特训",
    courseType: 2,
    courseTypeText: "私教",
    courseCategory: "体能",
    courseLevel: 2,
    courseLevelText: "中级",
    durationMinutes: 60,
    capacity: 1,
    enrollCount: 1,
    price: 400,
    coachId: 101,
    coachName: "王建国",
    location: "VIP训练室",
    startTime: "2024-10-01T00:00:00",
    endTime: "2025-06-30T00:00:00",
    status: 1,
    statusText: "进行中",
    courseDesc: "根据学员个人情况定制训练计划，全面提升体能素质。",
    courseDetail:
      "针对学员现有体能水平制定个性化训练方案，包含力量、耐力、爆发力、灵敏性等多维度训练。每课时结束后提供书面训练报告。",
    totalSessions: 24,
    completedSessions: 18,
    schedule: "预约制",
    scheduleTime: "1小时/节",
    studentIds: [2],
  },
  {
    id: 3,
    courseName: "成人健身塑形",
    courseType: 1,
    courseTypeText: "团课",
    courseCategory: "健身",
    courseLevel: 1,
    courseLevelText: "初级",
    durationMinutes: 90,
    capacity: 15,
    enrollCount: 12,
    price: 1800,
    coachId: 101,
    coachName: "王建国",
    location: "2号场馆",
    startTime: "2024-09-15T19:00:00",
    endTime: "2025-06-30T20:30:00",
    status: 1,
    statusText: "进行中",
    courseDesc: "针对成年人的健身塑形课程，结合有氧运动和力量训练。",
    courseDetail:
      "课程内容包含热身、核心力量、有氧燃脂、拉伸放松四个环节，每期36课时，每周三次，配合营养指导服务。",
    totalSessions: 36,
    completedSessions: 24,
    schedule: "周一、周三、周五",
    scheduleTime: "19:00 - 20:30",
    studentIds: [4, 7, 13, 14, 15],
  },
  {
    id: 4,
    courseName: "游泳入门班",
    courseType: 1,
    courseTypeText: "团课",
    courseCategory: "游泳",
    courseLevel: 1,
    courseLevelText: "初级",
    durationMinutes: 90,
    capacity: 8,
    enrollCount: 3,
    enrollmentRequirements: "6岁以上，不限基础",
    price: 3200,
    coachId: 101,
    coachName: "王建国",
    location: "游泳馆",
    startTime: "2025-03-01T10:00:00",
    endTime: "2025-06-30T11:30:00",
    status: 0,
    statusText: "招生中",
    courseDesc: "从零开始学游泳，安全有趣，适合各年龄段学员。",
    courseDetail:
      "课程从水上安全教育开始，逐步学习自由泳、蛙泳技术要领，共24课时。小班教学，每班不超过8人，确保教学质量。",
    totalSessions: 24,
    completedSessions: 0,
    schedule: "周末",
    scheduleTime: "10:00 - 11:30",
    studentIds: [3, 16, 17],
  },
]

// ============ 今日课程排期 ============
export const mockTodaySchedule = [
  {
    id: 101,
    courseId: 1,
    courseName: "青少年篮球训练",
    location: "A馆篮球场",
    startTime: "09:00",
    endTime: "10:30",
    timeRange: "09:00 - 10:30",
    date: "2025-03-12",
    students: 8,
    maxStudents: 20,
    status: 1,
    statusText: "进行中",
    checkedIn: 7,
    sessionNo: 33,
    notes: "今日重点练习三分投篮和快攻配合",
  },
  {
    id: 102,
    courseId: 2,
    courseName: "私教课 - 李明",
    location: "VIP训练室",
    startTime: "11:00",
    endTime: "12:00",
    timeRange: "11:00 - 12:00",
    date: "2025-03-12",
    students: 1,
    maxStudents: 1,
    status: 2,
    statusText: "即将开始",
    checkedIn: 0,
    sessionNo: 19,
    notes: "本节重点：上肢力量专项训练",
  },
  {
    id: 103,
    courseId: 3,
    courseName: "成人体能训练",
    location: "2号场馆",
    startTime: "14:00",
    endTime: "15:30",
    timeRange: "14:00 - 15:30",
    date: "2025-03-12",
    students: 12,
    maxStudents: 15,
    status: 0,
    statusText: "待开始",
    checkedIn: 0,
    sessionNo: 25,
    notes: "",
  },
  {
    id: 104,
    courseId: 4,
    courseName: "游泳技巧提升",
    location: "游泳馆",
    startTime: "16:00",
    endTime: "17:30",
    timeRange: "16:00 - 17:30",
    date: "2025-03-12",
    students: 6,
    maxStudents: 8,
    status: 0,
    statusText: "待开始",
    checkedIn: 0,
    sessionNo: 5,
    notes: "",
  },
]

// ============ 学员列表 ============
export const mockStudents = [
  {
    id: 1,
    childId: 201,
    name: "张三",
    avatar: null,
    courseId: 1,
    courseName: "青少年篮球训练营",
    remainingSessions: 12,
    totalSessions: 48,
    usedSessions: 36,
    lastClassDate: "2025-03-10",
    lastClassDaysAgo: "2天前",
    status: 1,
    statusText: "活跃",
    phone: "138****1234",
    parentName: "张国强",
    parentPhone: "138****1234",
    age: 12,
    gender: "男",
    enrollmentDate: "2024-09-01",
    attendanceRate: 94,
    notes: "投篮准确性有待提升，防守积极",
  },
  {
    id: 2,
    childId: 202,
    name: "李明",
    avatar: null,
    courseId: 2,
    courseName: "私教体能特训",
    remainingSessions: 6,
    totalSessions: 24,
    usedSessions: 18,
    lastClassDate: "2025-03-12",
    lastClassDaysAgo: "今天",
    status: 1,
    statusText: "活跃",
    phone: "139****5678",
    parentName: null,
    parentPhone: null,
    age: 28,
    gender: "男",
    enrollmentDate: "2024-10-15",
    attendanceRate: 100,
    notes: "自律性强，训练刻苦",
  },
  {
    id: 3,
    childId: 203,
    name: "王芳",
    avatar: null,
    courseId: 4,
    courseName: "游泳入门班",
    remainingSessions: 3,
    totalSessions: 24,
    usedSessions: 21,
    lastClassDate: "2025-03-07",
    lastClassDaysAgo: "5天前",
    status: 2,
    statusText: "课时不足",
    phone: "137****9012",
    parentName: "王建文",
    parentPhone: "137****9012",
    age: 10,
    gender: "女",
    enrollmentDate: "2024-11-01",
    attendanceRate: 87,
    notes: "已克服恐水心理，进步明显",
  },
  {
    id: 4,
    childId: 204,
    name: "陈伟",
    avatar: null,
    courseId: 3,
    courseName: "成人健身塑形",
    remainingSessions: 20,
    totalSessions: 36,
    usedSessions: 16,
    lastClassDate: "2025-03-11",
    lastClassDaysAgo: "1天前",
    status: 1,
    statusText: "活跃",
    phone: "136****3456",
    parentName: null,
    parentPhone: null,
    age: 35,
    gender: "男",
    enrollmentDate: "2024-09-15",
    attendanceRate: 89,
    notes: "目标减重15斤，已减重8斤",
  },
  {
    id: 5,
    childId: 205,
    name: "刘洋",
    avatar: null,
    courseId: 1,
    courseName: "青少年篮球训练营",
    remainingSessions: 0,
    totalSessions: 48,
    usedSessions: 48,
    lastClassDate: "2025-02-26",
    lastClassDaysAgo: "2周前",
    status: 3,
    statusText: "已结课",
    phone: "135****7890",
    parentName: "刘海波",
    parentPhone: "135****7890",
    age: 13,
    gender: "男",
    enrollmentDate: "2024-09-01",
    attendanceRate: 100,
    notes: "技术全面，建议续报进阶班",
  },
  {
    id: 6,
    childId: 206,
    name: "赵小红",
    avatar: null,
    courseId: 1,
    courseName: "青少年篮球训练营",
    remainingSessions: 16,
    totalSessions: 48,
    usedSessions: 32,
    lastClassDate: "2025-03-08",
    lastClassDaysAgo: "4天前",
    status: 1,
    statusText: "活跃",
    phone: "134****2345",
    parentName: "赵明远",
    parentPhone: "134****2345",
    age: 11,
    gender: "女",
    enrollmentDate: "2024-09-01",
    attendanceRate: 91,
    notes: "女生中篮球天赋突出",
  },
  {
    id: 7,
    childId: 207,
    name: "孙鹏",
    avatar: null,
    courseId: 3,
    courseName: "成人健身塑形",
    remainingSessions: 5,
    totalSessions: 36,
    usedSessions: 31,
    lastClassDate: "2025-03-09",
    lastClassDaysAgo: "3天前",
    status: 2,
    statusText: "课时不足",
    phone: "133****6789",
    parentName: null,
    parentPhone: null,
    age: 42,
    gender: "男",
    enrollmentDate: "2024-09-15",
    attendanceRate: 86,
    notes: "体重管理效果良好",
  },
]

// ============ 学员上课记录 ============
export const mockStudentClassHistory: Record<number, { date: string; courseName: string; sessionNo: number; attended: boolean; feedback?: string }[]> = {
  1: [
    { date: "2025-03-10", courseName: "青少年篮球训练营", sessionNo: 32, attended: true, feedback: "运球和传球配合越来越默契" },
    { date: "2025-03-06", courseName: "青少年篮球训练营", sessionNo: 31, attended: true, feedback: "投篮练习表现积极" },
    { date: "2025-03-04", courseName: "青少年篮球训练营", sessionNo: 30, attended: false },
    { date: "2025-02-27", courseName: "青少年篮球训练营", sessionNo: 29, attended: true, feedback: "防守意识明显提升" },
    { date: "2025-02-25", courseName: "青少年篮球训练营", sessionNo: 28, attended: true },
  ],
  2: [
    { date: "2025-03-12", courseName: "私教体能特训", sessionNo: 18, attended: true, feedback: "上肢力量提升显著" },
    { date: "2025-03-10", courseName: "私教体能特训", sessionNo: 17, attended: true, feedback: "核心稳定性训练完成良好" },
    { date: "2025-03-07", courseName: "私教体能特训", sessionNo: 16, attended: true },
    { date: "2025-03-05", courseName: "私教体能特训", sessionNo: 15, attended: true, feedback: "爆发力测试进步3%" },
    { date: "2025-03-03", courseName: "私教体能特训", sessionNo: 14, attended: true },
  ],
  3: [
    { date: "2025-03-07", courseName: "游泳入门班", sessionNo: 5, attended: true, feedback: "自由泳手臂动作有进步" },
    { date: "2025-03-01", courseName: "游泳入门班", sessionNo: 4, attended: true, feedback: "换气技术需要加强练习" },
    { date: "2025-02-22", courseName: "游泳入门班", sessionNo: 3, attended: false },
    { date: "2025-02-15", courseName: "游泳入门班", sessionNo: 2, attended: true },
    { date: "2025-02-08", courseName: "游泳入门班", sessionNo: 1, attended: true, feedback: "克服恐水心理，成功完成水中行走" },
  ],
}

// ============ 教学反馈 TeachingFeedbackVO ============
export const mockTeachingFeedbacks = [
  {
    id: 1,
    childId: 201,
    childName: "张三",
    courseId: 1,
    courseName: "青少年篮球训练营",
    coachId: 101,
    coachName: "王建国",
    classDate: "2025-03-10T09:00:00",
    sessionNo: 32,
    content:
      "今天张三在运球训练中表现出色，左右手运球配合越来越协调。建议继续加强投篮准确性练习，课后可以进行15分钟的定点投篮训练。整体进步明显，值得鼓励！",
    images: null,
    status: 1,
    statusText: "已反馈",
    parentViewed: 1,
    parentViewedText: "已查看",
    createTime: "2025-03-10T11:30:00",
    updateTime: "2025-03-10T11:30:00",
  },
  {
    id: 2,
    childId: 203,
    childName: "王芳",
    courseId: 4,
    courseName: "游泳入门班",
    coachId: 101,
    coachName: "王建国",
    classDate: "2025-03-07T10:00:00",
    sessionNo: 5,
    content:
      "王芳今天克服了对水的恐惧，成功完成了第一次自由泳练习。虽然动作还不够规范，但心理突破非常重要。下节课将重点纠正手部划水动作。",
    images: null,
    status: 1,
    statusText: "已反馈",
    parentViewed: 0,
    parentViewedText: "未查看",
    createTime: "2025-03-07T12:00:00",
    updateTime: "2025-03-07T12:00:00",
  },
  {
    id: 3,
    childId: 206,
    childName: "赵小红",
    courseId: 1,
    courseName: "青少年篮球训练营",
    coachId: 101,
    coachName: "王建国",
    classDate: "2025-03-08T09:00:00",
    sessionNo: 31,
    content: null,
    images: null,
    status: 2,
    statusText: "待反馈",
    parentViewed: 0,
    parentViewedText: "未查看",
    createTime: "2025-03-08T10:30:00",
    updateTime: "2025-03-08T10:30:00",
  },
  {
    id: 4,
    childId: 201,
    childName: "张三",
    courseId: 1,
    courseName: "青少年篮球训练营",
    coachId: 101,
    coachName: "王建国",
    classDate: "2025-03-06T09:00:00",
    sessionNo: 31,
    content:
      "本次训练重点进行了3对3对抗练习。张三的防守意识有明显提升，但进攻时容易急躁，需要加强冷静判断能力。建议家长鼓励孩子在日常生活中培养耐心。",
    images: null,
    status: 1,
    statusText: "已反馈",
    parentViewed: 1,
    parentViewedText: "已查看",
    createTime: "2025-03-06T11:00:00",
    updateTime: "2025-03-06T11:00:00",
  },
  {
    id: 5,
    childId: 202,
    childName: "李明",
    courseId: 2,
    courseName: "私教体能特训",
    coachId: 101,
    coachName: "王建国",
    classDate: "2025-03-12T11:00:00",
    sessionNo: 18,
    content: null,
    images: null,
    status: 2,
    statusText: "待反馈",
    parentViewed: 0,
    parentViewedText: "未查看",
    createTime: "2025-03-12T12:00:00",
    updateTime: "2025-03-12T12:00:00",
  },
]

// ============ 消息中心 ============
export const mockMessages = [
  {
    id: 1,
    type: "booking",
    title: "新的课程预约",
    content: "李明 预约了明天 14:00 的私教课程",
    detail: "学员李明（私教体能特训）通过系统提交了预约申请，预约时间：2025年3月13日 14:00-15:00，地点：VIP训练室。请确认是否接受此预约。",
    time: "5分钟前",
    unread: true,
    actions: ["确认预约", "拒绝预约"],
  },
  {
    id: 2,
    type: "system",
    title: "课时提醒",
    content: "学员王芳的课时仅剩3节，请及时跟进续费",
    detail: "学员王芳（游泳入门班）当前课时余量仅剩3节，按照正常上课频率预计将于2025年3月底耗尽。建议及时联系家长办理续费，避免课程中断影响学习进度。",
    time: "1小时前",
    unread: true,
    actions: ["联系家长"],
  },
  {
    id: 3,
    type: "message",
    title: "学员消息",
    content: "张三: 教练您好，请问明天的课程可以调整时间吗？",
    detail: "张三（家长：张国强）发来消息：\n教练您好，孩子明天上午有学校活动，无法按时参加09:00的篮球课，请问是否可以调整到下午14:00-15:30？如果不方便调整，请假一次也可以，感谢！",
    time: "2小时前",
    unread: true,
    sender: "张三",
    actions: ["回复消息"],
  },
  {
    id: 4,
    type: "alert",
    title: "场馆通知",
    content: "A馆篮球场明天下午进行维护，请提前调整课程",
    detail: "场馆管理通知：A馆篮球场将于2025年3月13日下午14:00-17:00进行地板维护作业，期间无法正常使用。如您有排课安排，请提前与场馆协调更换场地或调整时间，造成不便敬请谅解。",
    time: "3小时前",
    unread: false,
    actions: [],
  },
  {
    id: 5,
    type: "booking",
    title: "课程取消",
    content: "陈伟 取消了今天 16:00 的体能训练课程",
    detail: "学员陈伟（成人健身塑形）申请取消今日16:00课程，原因：临时出差。本次取消不扣除课时，课时已自动返还至账户。",
    time: "今天 10:23",
    unread: false,
    actions: [],
  },
  {
    id: 6,
    type: "feedback",
    title: "教学反馈提醒",
    content: "赵小红 上次课程反馈尚未填写，请尽快完成",
    detail: "系统提醒：学员赵小红（青少年篮球训练营）2025年3月8日第31课时的教学反馈尚未填写。家长已多次查看是否有反馈更新，请尽快完成填写，及时向家长反馈孩子的学习情况。",
    time: "昨天 18:00",
    unread: false,
    actions: ["立即填写"],
  },
]

// ============ 首页统计数据 ============
export const mockHomeStats = {
  todayStudents: 28,
  todayStudentsChange: "+3",
  weekCourses: 14,
  weekCoursesChange: "+2",
  monthHours: 42,
  monthHoursChange: "+5h",
  completionRate: 96,
  completionRateChange: "+1%",
}

// ============ 课程日历数据 ============
export const mockCalendarCourses = [
  {
    date: "2025-03-12",
    courses: [
      { id: 101, courseId: 1, courseName: "青少年篮球", time: "09:00-10:30", location: "A馆篮球场", students: 8, status: 1 },
      { id: 102, courseId: 2, courseName: "私教 - 李明", time: "11:00-12:00", location: "VIP训练室", students: 1, status: 2 },
      { id: 103, courseId: 3, courseName: "成人体能", time: "14:00-15:30", location: "2号场馆", students: 12, status: 0 },
      { id: 104, courseId: 4, courseName: "游泳技巧", time: "16:00-17:30", location: "游泳馆", students: 6, status: 0 },
    ],
  },
  {
    date: "2025-03-13",
    courses: [
      { id: 105, courseId: 3, courseName: "成人体能", time: "19:00-20:30", location: "2号场馆", students: 11, status: 0 },
    ],
  },
  {
    date: "2025-03-14",
    courses: [
      { id: 106, courseId: 1, courseName: "青少年篮球", time: "09:00-10:30", location: "A馆篮球场", students: 8, status: 0 },
      { id: 107, courseId: 3, courseName: "成人体能", time: "14:00-15:30", location: "2号场馆", students: 12, status: 0 },
    ],
  },
  {
    date: "2025-03-15",
    courses: [
      { id: 108, courseId: 1, courseName: "青少年篮球", time: "09:00-10:30", location: "A馆篮球场", students: 8, status: 0 },
      { id: 109, courseId: 4, courseName: "游泳入门", time: "10:00-11:30", location: "游泳馆", students: 6, status: 0 },
    ],
  },
]

// ============ 签到记录（按场次ID） ============
export const mockSessionAttendance: Record<number, { childId: number; name: string; attended: boolean; checkInTime: string | null; reason?: string }[]> = {
  101: [
    { childId: 201, name: "张三",   attended: true,  checkInTime: "08:55" },
    { childId: 206, name: "赵小红", attended: true,  checkInTime: "09:02" },
    { childId: 205, name: "刘洋",   attended: false, checkInTime: null, reason: "请假" },
    { childId: 208, name: "周浩",   attended: true,  checkInTime: "09:00" },
    { childId: 209, name: "吴磊",   attended: true,  checkInTime: "08:58" },
    { childId: 210, name: "郑涛",   attended: true,  checkInTime: "09:05" },
    { childId: 211, name: "黄梅",   attended: true,  checkInTime: "08:52" },
    { childId: 212, name: "林晓",   attended: true,  checkInTime: "09:01" },
  ],
  102: [
    { childId: 202, name: "李明", attended: false, checkInTime: null },
  ],
  103: [
    { childId: 204, name: "陈伟",  attended: false, checkInTime: null },
    { childId: 207, name: "孙鹏",  attended: false, checkInTime: null },
    { childId: 213, name: "何静",  attended: false, checkInTime: null },
    { childId: 214, name: "蒋磊",  attended: false, checkInTime: null },
    { childId: 215, name: "韩雪",  attended: false, checkInTime: null },
    { childId: 216, name: "冯亮",  attended: false, checkInTime: null },
    { childId: 217, name: "钱伟",  attended: false, checkInTime: null },
    { childId: 218, name: "沈芳",  attended: false, checkInTime: null },
    { childId: 219, name: "朱浩",  attended: false, checkInTime: null },
    { childId: 220, name: "赵磊",  attended: false, checkInTime: null },
    { childId: 221, name: "周敏",  attended: false, checkInTime: null },
    { childId: 222, name: "吴刚",  attended: false, checkInTime: null },
  ],
  104: [
    { childId: 203, name: "王芳",  attended: false, checkInTime: null },
    { childId: 223, name: "张磊",  attended: false, checkInTime: null },
    { childId: 224, name: "李红",  attended: false, checkInTime: null },
    { childId: 225, name: "刘强",  attended: false, checkInTime: null },
    { childId: 226, name: "陈华",  attended: false, checkInTime: null },
    { childId: 227, name: "杨洋",  attended: false, checkInTime: null },
  ],
}

// 旧的签到数据（兼容）
export const mockAttendanceRecords = [
  {
    sessionId: 101,
    courseId: 1,
    courseName: "青少年篮球训练营",
    date: "2025-03-12",
    startTime: "09:00",
    endTime: "10:30",
    location: "A馆篮球场",
    totalStudents: 8,
    presentCount: 7,
    absentCount: 1,
    students: mockSessionAttendance[101],
  },
]
